### ISSUE TITLE
Support for Koa

### ISSUE THREAD

**Issue by cooperka** [fortunejs/fortune-http#11]
It seems that Fortune HTTP relies on several low-level methods such as `response.writeHead`.

[Koa](http://koajs.com/), a web framework designed by the team behind [Express](http://expressjs.com/), provides access to Node's `response` object but [explicitly states](https://github.com/koajs/koa/blob/master/docs/api/context.md#api):

> Bypassing Koa's response handling is **not supported**. Avoid using the following node properties:
>
> - res.statusCode
> - res.writeHead()
> - res.write()
> - res.end()

Indeed, trying to pass `ctx.req` and `ctx.res` to the `fortuneHttp()` listener results in errors:

```
RangeError: Invalid status code: null
```

and

```
Error: Can't remove headers after they are sent
```

Is there any planned support for Koa? It's an awesome framework that would be great to be able to use. For now, I'll use Express instead.

Thank you for any clarity you can provide!

**Comment by gr0uch** [comment]
I'm not sure how to best handle this since I have never used Koa, and Express seems to be far more popular, API compatibility may be a reason for that.

It sounds like a big no-no, because `fortune-http` does all of the things listed under "avoid".

**Comment by cooperka** [comment]
Clear and concise answer, thanks. I'm okay with that decision; many of the original benefits of Koa (circa 2016) are now obsolete anyway since async/await works well with Express.
