### ISSUE TITLE
Make adding relationships easier

### ISSUE THREAD

**Issue by goranmoomin** [fortunejs/fortune-http#13]
When adding/editing relationships, the current way is to copy & paste the long ids manually.
Would it be hard to use the [select element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) to provide an appropriate list to select from to add/edit relationships?

**Comment by gr0uch** [comment]
I agree that the current text input isn't optimal. However it's also not really feasible to get a list of all IDs for large datasets, nor is it the best UX.
