### ISSUE TITLE
Adding custom arrays are impossible

### ISSUE THREAD

**Issue by goranmoomin** [fortunejs/fortune-http#14]
Currently with fortune-http relationship that are Array of Objects[] aren't editable as [the offending line](https://github.com/fortunejs/fortune-http/blob/master/lib/form_serializer.js#L162) slices the JSON into pieces.

**Comment by gr0uch** [comment]
There's not really any good use case for arrays of objects with the form serializer. If you actually are using an HTML form, users aren't going to be typing or pasting JSON anyways. Better use a JSON format for sending JSON rather than forms.

**Comment by goranmoomin** [comment]
@daliwali Yeah, that’s true, but I was supplying data for bootstrapping my API; I found it tedious to make curl requests just to supply some data (before any UI was made).
I just worked around this by making the whole type as an Array Object instead of an Array of Object...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
