### ISSUE TITLE
Stopped working after update to 1.0.6

### ISSUE THREAD

**Issue by OEvgeny** [fortunejs/fortune-http#8]
Hi.
Looks like something went wrong with the latest update. I can`t use fortune through `fortune-http` API any more.

Before update request like this one
```
curl 'http://localhost:3000/api/fortune/recall' -H 'Pragma: no-cache' -H 'Origin: http://localhost:8080' -H 'Accept-Encoding: gzip, deflate, sdch, br' -H 'Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.138 Safari/537.36 Vivaldi/1.8.770.56' -H 'Accept: application/json, text/plain, */*' -H 'Cache-Control: no-cache' -H 'Referer: http://localhost:8080/' -H 'Cookie: _ga=GA1.1.1036470260.1491330952;  connect.sid=s%3AKw-oFoBTn0N3wgQo1qaYjiavjLhE_ZBe.ZGS7MHoGNto0v4UC3Ajxf5Tddqmi66k4uyrwdPYZogE' -H 'Connection: keep-alive' -H 'DNT: 1' --compressed
```
returned raw string contained json.

After update it seems response containing gzipped json but I cant see any headers which signals about it.
Headers for this request:
```
X-Powered-By: Express
Access-Control-Allow-Origin: http://localhost:8080
Vary: Origin
Access-Control-Allow-Credentials: true
Date: Mon, 17 Apr 2017 20:58:24 GMT
Connection: keep-alive
```

I am using express to serve my api. So, problem can be in my config. If you have some idea why it may happen, please tell me.

Thank you for fortune!

**Comment by gr0uch** [comment]
Hi, sorry about that. There have been changes recently to accommodate an alternative HTTP implementation, namely `uws.http`, which improves network performance by a significant margin.

If I understand this correctly, the issue is that a `content-encoding` header is not set on the response?

**Comment by gr0uch** [comment]
I added a test for `content-encoding` negotiation: https://github.com/fortunejs/fortune-http/commit/c141cce4fd37bb2b83b7ed487abf3ce6fa6d0d53

The `content-encoding` header is correct. It seems fine from my side. By the way, you have `accept-encoding` in your `curl` example, could that be it?

**Comment by OEvgeny** [comment]
I copied request from Chrome. I am using axios on the client side to perform requests.  Also I tried to get to the html interface through Chrome. Both leads to getting gzipped content without provided headers.
So I going to investigate what can be wrong with my config in a few days.
Thanks for response!

**Comment by OEvgeny** [comment]
> If I understand this correctly, the issue is that a content-encoding header is not set on the response?

I think it could be the reason but tests shows what there is probably another problem. I think it can be near express and fortune-http integration on my side.

**Comment by gr0uch** [comment]
@OEvgeny did you figure this out?

**Comment by OEvgeny** [comment]
No, I looked into it a bit and couldn't figure out what is going wrong. So I will close it for now, and will try to reproduce it with only express. I will also reopen this with additional details if I got result.
